# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webopenface', '0002_auto_20160624_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mod_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
