# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webopenface', '0003_auto_20160624_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
