# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webopenface', '0004_auto_20160708_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedpeople',
            name='probability',
            field=models.SmallIntegerField(default=0),
        ),
    ]
