# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webopenface', '0005_detectedpeople_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedpeople',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webopenface.Person'),
        ),
    ]
